[package]
name = "assrt"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0"
syn = {version = "2.0", features = ["visit", "full", "extra-traits"] }
quote = "1.0"
itertools = "0.13"
